version: '3.8'

services:
  sa-id-validator:
    build: .
    container_name: sa-id-validator-desktop
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    network_mode: host
    stdin_open: true
    tty: true
